package schedulable;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.LinkedList;
import java.util.Queue;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author NagbontianAliciaBene
 */
public class BloodTestGUI extends javax.swing.JFrame {
        private BloodTestScheduler scheduler = new BloodTestScheduler();

    public BloodTestGUI() {
        initComponents();
    }
    
    private void updateDisplay() {
        displayTXT.setText(scheduler.getAllPatientsInfo());  
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameLBL = new javax.swing.JLabel();
        ageLBL = new javax.swing.JLabel();
        priorityLBL = new javax.swing.JLabel();
        gpLBL = new javax.swing.JLabel();
        nameTXT = new javax.swing.JTextField();
        ageTXT = new javax.swing.JTextField();
        gpTXT = new javax.swing.JTextField();
        priorityCMB = new javax.swing.JComboBox<>();
        hospitalCKB = new javax.swing.JCheckBox();
        addBTN = new javax.swing.JButton();
        nextBTN = new javax.swing.JButton();
        noShowBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTXT = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(113, 101, 0, 0);

        nameLBL.setText("name");
        getContentPane().add(nameLBL);
        nameLBL.setBounds(10, 30, 50, 16);

        ageLBL.setText("age");
        getContentPane().add(ageLBL);
        ageLBL.setBounds(9, 70, 50, 16);

        priorityLBL.setText("priority");
        getContentPane().add(priorityLBL);
        priorityLBL.setBounds(8, 110, 60, 16);

        gpLBL.setText("GP details");
        getContentPane().add(gpLBL);
        gpLBL.setBounds(2, 150, 70, 16);
        getContentPane().add(nameTXT);
        nameTXT.setBounds(80, 30, 100, 22);

        ageTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTXTActionPerformed(evt);
            }
        });
        getContentPane().add(ageTXT);
        ageTXT.setBounds(80, 70, 100, 22);
        getContentPane().add(gpTXT);
        gpTXT.setBounds(80, 148, 100, 22);

        priorityCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urgent", "Medium", "Low" }));
        priorityCMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priorityCMBActionPerformed(evt);
            }
        });
        getContentPane().add(priorityCMB);
        priorityCMB.setBounds(80, 110, 100, 22);

        hospitalCKB.setText("From Hospital?");
        getContentPane().add(hospitalCKB);
        hospitalCKB.setBounds(370, 290, 140, 20);

        addBTN.setText("add patient");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });
        getContentPane().add(addBTN);
        addBTN.setBounds(240, 290, 90, 23);

        nextBTN.setText("next patient");
        nextBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBTNActionPerformed(evt);
            }
        });
        getContentPane().add(nextBTN);
        nextBTN.setBounds(130, 290, 93, 23);

        noShowBTN.setText("no show");
        noShowBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noShowBTNActionPerformed(evt);
            }
        });
        getContentPane().add(noShowBTN);
        noShowBTN.setBounds(40, 290, 75, 23);

        displayTXT.setEditable(false);
        displayTXT.setColumns(20);
        displayTXT.setRows(5);
        jScrollPane1.setViewportView(displayTXT);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 190, 234, 88);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void priorityCMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priorityCMBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priorityCMBActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
            try {
        String name = nameTXT.getText();
        int age = Integer.parseInt(ageTXT.getText());  // Converts age safely
        String gp = gpTXT.getText();
        String priority = (String) priorityCMB.getSelectedItem();
        boolean fromHospital = hospitalCKB.isSelected();

        scheduler.addPerson(new Person(name, age, priority, gp, fromHospital));
        updateDisplay();  

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Enter a valid number for age!", "Input Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_addBTNActionPerformed

    private void nextBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBTNActionPerformed
        // TODO add your handling code here:
        Person next = scheduler.getNextPerson();
        if (next != null) {
            JOptionPane.showMessageDialog(this, "Next: " + next);
        } else {
            JOptionPane.showMessageDialog(this, "No patients in queue.");
        }
        updateDisplay();
    }//GEN-LAST:event_nextBTNActionPerformed

    private void noShowBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noShowBTNActionPerformed
        // TODO add your handling code here:
            Person next = scheduler.peekNextPerson();  

    if (next != null) {
        JOptionPane.showMessageDialog(this, "Marked as No-Show: " + next.getName());

        // Remove them from the queue after marking as a no-show
        scheduler.getNextPerson();
    } else {
        JOptionPane.showMessageDialog(this, "No patients to mark as no-show.");
    }

    updateDisplay();
    }//GEN-LAST:event_noShowBTNActionPerformed

    private void ageTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTXTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BloodTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BloodTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BloodTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BloodTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BloodTestGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JLabel ageLBL;
    private javax.swing.JTextField ageTXT;
    private javax.swing.JTextArea displayTXT;
    private javax.swing.JLabel gpLBL;
    private javax.swing.JTextField gpTXT;
    private javax.swing.JCheckBox hospitalCKB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTXT;
    private javax.swing.JButton nextBTN;
    private javax.swing.JButton noShowBTN;
    private javax.swing.JComboBox<String> priorityCMB;
    private javax.swing.JLabel priorityLBL;
    // End of variables declaration//GEN-END:variables
}
